use_frameworks!

platform :ios, '8.0'

target 'PatternLock_Example' do
  pod 'PatternLock', :path => '../'

  target 'PatternLock_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
